//
// Created by astra on 2022/2/15.
//

#ifndef SFML_PROJECT_FONTNAMES_H
#define SFML_PROJECT_FONTNAMES_H

enum FontNames{
    OPENSANSBOLD, ARIAL, STAMPERCMUP, BRAGGATITULDCFR, ANTIQUASH_ITALIC,

    LASTFONT
};
#endif //SFML_PROJECT_FONTNAMES_H
